# Generated by Django 3.0.7 on 2020-06-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='')),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('A', 'A'), ('AA', 'AA'), ('AAA', 'AAA')], max_length=3, null=True)),
                ('developer', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('min_graphics_level', models.IntegerField()),
                ('min_processor_level', models.IntegerField()),
                ('min_memory_level', models.IntegerField()),
                ('max_graphics_level', models.IntegerField()),
                ('max_processor_level', models.IntegerField()),
                ('max_memory_level', models.IntegerField()),
            ],
        ),
    ]
