# Generated by Django 3.0.7 on 2020-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Apple', 'Apple'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='computer',
            name='graphics_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='computer',
            name='memory_level',
            field=models.FloatField(choices=[(1, '1GB'), (2, '2GB'), (3, '4GB'), (4, '6GB'), (5, '8GB'), (6, '12GB'), (7, '14GB'), (8, '16GB'), (9, '32GB'), (10, '64GB+')]),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='max_graphics_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='max_memory_level',
            field=models.FloatField(choices=[(1, '1GB'), (2, '2GB'), (3, '4GB'), (4, '6GB'), (5, '8GB'), (6, '12GB'), (7, '14GB'), (8, '16GB'), (9, '32GB'), (10, '64GB+')]),
        ),
        migrations.AlterField(
            model_name='software',
            name='max_processor_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='min_graphics_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='software',
            name='min_memory_level',
            field=models.FloatField(choices=[(1, '1GB'), (2, '2GB'), (3, '4GB'), (4, '6GB'), (5, '8GB'), (6, '12GB'), (7, '14GB'), (8, '16GB'), (9, '32GB'), (10, '64GB+')]),
        ),
        migrations.AlterField(
            model_name='software',
            name='min_processor_level',
            field=models.FloatField(),
        ),
    ]
