# Generated by Django 3.0.7 on 2020-06-20 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0002_auto_20200620_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
