# Generated by Django 3.0.7 on 2020-06-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0003_auto_20200620_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='computers')),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Apple', 'Apple'), ('Other', 'Other')], max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('affiliate_link', models.URLField()),
                ('graphics_level', models.IntegerField()),
                ('processor_level', models.IntegerField()),
                ('memory_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='softwares'),
        ),
    ]
