# Generated by Django 3.0.7 on 2020-06-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20200621_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='price',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.CharField(choices=[('Notebook', 'Notebook'), ('Desktop', 'Desktop'), ('Apple', 'Apple'), ('Other', 'Other')], max_length=100),
        ),
    ]
